// Package python generates complete Python projects from workflows.
//
// The Python Generator produces a standard Python project structure:
//
//	project-name/
//	├── .aistudio/
//	│   └── workflow.json
//	├── src/
//	│   ├── __init__.py
//	│   ├── data_loader.py
//	│   ├── model.py
//	│   ├── train.py
//	│   └── utils.py
//	├── config/
//	│   └── config.yaml
//	├── data/
//	├── models/
//	├── outputs/
//	├── tests/
//	│   └── __init__.py
//	├── requirements.txt
//	├── setup.py
//	├── main.py
//	├── README.md
//	└── .gitignore
//
// The generated project is a real, runnable Python project that can
// be executed independently of AIStudio.
package python

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/aistudio/backend/internal/compiler"
	"github.com/aistudio/backend/internal/workflow"
)

// Generator generates Python projects from workflows.
type Generator struct {
	compiler.BaseGenerator
}

// NewGenerator creates a new Python Generator.
func NewGenerator() *Generator {
	return &Generator{
		BaseGenerator: compiler.BaseGenerator{
			TargetID:      workflow.TargetPython,
			GeneratorName: "Python Project Generator",
			GeneratorDesc: "Generates standard Python projects with proper structure, dependencies, and entry points",
			GeneratorVer:  "2.0.0",
		},
	}
}

func (g *Generator) Validate(wf *workflow.Workflow) error {
	return g.DefaultValidate(wf)
}

func (g *Generator) EstimateResources(wf *workflow.Workflow) (*compiler.ResourceEstimate, error) {
	return g.DefaultEstimateResources(wf)
}

func (g *Generator) CompileTimeValidate(ctx context.Context) error {
	return g.DefaultCompileTimeValidate(ctx)
}

func (g *Generator) RuntimeRequirement(wf *workflow.Workflow) (*compiler.RuntimeRequirement, error) {
	pkgs := g.collectPackages(wf)
	return &compiler.RuntimeRequirement{
		Name:     "python",
		Version:  "3.9+",
		Python:   ">=3.9",
		Packages: pkgs,
		Commands: []string{"python", "pip"},
		GPU:      g.requiresGPU(wf),
	}, nil
}

func (g *Generator) Generate(ctx context.Context, wf *workflow.Workflow, opts compiler.CompileOptions) (*compiler.GenerateResult, error) {
	// Determine project name
	projectName := opts.ProjectName
	if projectName == "" {
		projectName = sanitizeName(wf.Name)
	}

	// Determine output directory
	outputDir := opts.OutputDir
	if outputDir == "" {
		outputDir = filepath.Join(".", projectName)
	}

	// Check if output directory exists
	if !opts.Force {
		if _, err := os.Stat(outputDir); err == nil {
			return nil, fmt.Errorf("output directory already exists: %s (use Force=true to overwrite)", outputDir)
		}
	}

	// Create project structure
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create output directory: %w", err)
	}

	var files []compiler.GeneratedFile

	// Generate files
	files = append(files, g.generateMainPy(wf, projectName)...)
	files = append(files, g.generateRequirements(wf)...)
	files = append(files, g.generateSetupPy(wf, projectName)...)
	files = append(files, g.generateConfigYaml(wf)...)
	files = append(files, g.generateGitignore()...)
	files = append(files, g.generateReadme(wf, projectName)...)
	files = append(files, g.generateSourceFiles(wf)...)
	files = append(files, g.generateTestFiles()...)
	files = append(files, g.generateWorkflowCopy(wf)...)

	// Write files to disk
	entryPoints := []string{filepath.Join(outputDir, "main.py")}
	for _, f := range files {
		fullPath := filepath.Join(outputDir, f.Path)
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return nil, fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
		if err := os.WriteFile(fullPath, []byte(f.Content), os.FileMode(f.Mode)); err != nil {
			return nil, fmt.Errorf("failed to write file %s: %w", f.Path, err)
		}
	}

	return &compiler.GenerateResult{
		Target:      workflow.TargetPython,
		ProjectRoot: outputDir,
		EntryPoints: entryPoints,
		Files:       files,
		ProjectName: projectName,
	}, nil
}

// ============================================================================
// File Generators
// ============================================================================

func (g *Generator) generateMainPy(wf *workflow.Workflow, projectName string) []compiler.GeneratedFile {
	sorted, _ := workflow.TopologicalSort(wf)

	var nodeImports []string
	var nodeExecutions []string
	for _, node := range sorted {
		importName := fmt.Sprintf("from src.%s import %s", sanitizeName(node.Name), sanitizeFuncName(node.Name))
		nodeImports = append(nodeImports, importName)
		nodeExecutions = append(nodeExecutions, fmt.Sprintf("    # Execute: %s (%s)", node.Name, node.Type))
	}

	content := fmt.Sprintf(`#!/usr/bin/env python3
"""
%s

Generated by AIStudio Python Generator
Workflow: %s (%s)
Target: %s
"""

import os
import sys
import yaml
import logging
from pathlib import Path

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="[%%(asctime)s] %%(levelname)s - %%(message)s",
    datefmt="%%Y-%%m-%%d %%H:%%M:%%S",
)
logger = logging.getLogger(__name__)

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

# Load configuration
def load_config():
    config_path = Path(__file__).parent / "config" / "config.yaml"
    if config_path.exists():
        with open(config_path, "r") as f:
            return yaml.safe_load(f)
    return {}

# Import workflow modules
%s

def main():
    """Main entry point - executes the workflow DAG."""
    logger.info("Starting workflow: %%s", %q)
    config = load_config()

    # Execute workflow nodes in topological order
%s

    logger.info("Workflow completed successfully")

if __name__ == "__main__":
    main()
`, projectName, wf.Name, wf.ID, wf.Target,
		strings.Join(nodeImports, "\n"),
		wf.Name,
		strings.Join(nodeExecutions, "\n"))

	return []compiler.GeneratedFile{
		{Path: "main.py", Content: content, Mode: 0755},
	}
}

func (g *Generator) generateRequirements(wf *workflow.Workflow) []compiler.GeneratedFile {
	pkgs := g.collectPackages(wf)
	content := fmt.Sprintf(`# AIStudio Generated Requirements
# Workflow: %s (%s)

%s
`, wf.Name, wf.ID, strings.Join(pkgs, "\n"))

	return []compiler.GeneratedFile{
		{Path: "requirements.txt", Content: content, Mode: 0644},
	}
}

func (g *Generator) generateSetupPy(wf *workflow.Workflow, projectName string) []compiler.GeneratedFile {
	content := fmt.Sprintf(`#!/usr/bin/env python3
"""Setup script for %s."""

from setuptools import setup, find_packages

setup(
    name="%s",
    version="1.0.0",
    description="%s",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "pyyaml>=6.0",
    ],
)
`, projectName, projectName, wf.Description)

	return []compiler.GeneratedFile{
		{Path: "setup.py", Content: content, Mode: 0644},
	}
}

func (g *Generator) generateConfigYaml(wf *workflow.Workflow) []compiler.GeneratedFile {
	// Generate config from workflow variables
	var vars []string
	for k, v := range wf.Variables {
		vars = append(vars, fmt.Sprintf("# %s: %v", k, v))
	}

	content := fmt.Sprintf(`# AIStudio Generated Configuration
# Workflow: %s (%s)

workflow:
  id: %s
  name: %s
  version: %d

# Workflow Variables
%s
`, wf.Name, wf.ID, wf.ID, wf.Name, wf.Version, strings.Join(vars, "\n"))

	return []compiler.GeneratedFile{
		{Path: "config/config.yaml", Content: content, Mode: 0644},
	}
}

func (g *Generator) generateGitignore() []compiler.GeneratedFile {
	content := `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
*.egg-info/
dist/
build/
*.egg

# Virtual environments
venv/
.venv/
env/

# IDE
.idea/
.vscode/
*.swp
*.swo

# AIStudio
.aistudio/

# Data and models
data/
models/
outputs/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
`
	return []compiler.GeneratedFile{
		{Path: ".gitignore", Content: content, Mode: 0644},
	}
}

func (g *Generator) generateReadme(wf *workflow.Workflow, projectName string) []compiler.GeneratedFile {
	header := fmt.Sprintf("# %s\n\n%s\n\n## Overview\n\nThis project was generated by AIStudio from workflow: **%s**.\n\n",
		projectName, wf.Description, wf.Name)

	structure := "## Project Structure\n\n" +
		"```\n.\n" +
		"\u251C\u2500\u2500 src/              # Source code\n" +
		"\u251C\u2500\u2500 config/           # Configuration\n" +
		"\u251C\u2500\u2500 data/             # Data directory\n" +
		"\u251C\u2500\u2500 models/           # Model outputs\n" +
		"\u251C\u2500\u2500 outputs/          # Execution outputs\n" +
		"\u251C\u2500\u2500 tests/            # Unit tests\n" +
		"\u251C\u2500\u2500 main.py           # Entry point\n" +
		"\u251C\u2500\u2500 requirements.txt  # Python dependencies\n" +
		"\u2514\u2500\u2500 setup.py          # Package setup\n" +
		"```\n\n"

	usage := "## Usage\n\n### Install dependencies\n\n" +
		"```bash\npip install -r requirements.txt\n```\n\n" +
		"### Run\n\n```bash\npython main.py\n```\n\n" +
		"### Development\n\n```bash\npip install -e .\n```\n\n"

	table := "## Workflow\n\nThis project implements the following workflow:\n\n" +
		"| Node | Type | Description |\n|------|------|-------------|\n"

	content := header + structure + usage + table

	for _, node := range wf.Nodes {
		content += fmt.Sprintf("| %s | %s | %s |\n", node.Name, node.Type, node.Description)
	}

	content += "\n---\n_Generated by AIStudio_\n"

	return []compiler.GeneratedFile{
		{Path: "README.md", Content: content, Mode: 0644},
	}
}

func (g *Generator) generateSourceFiles(wf *workflow.Workflow) []compiler.GeneratedFile {
	var files []compiler.GeneratedFile

	// __init__.py
	files = append(files, compiler.GeneratedFile{
		Path: "src/__init__.py", Content: `"""AIStudio Generated Python Project."""
`, Mode: 0644})

	// Generate module files for each node type
	seenTypes := make(map[workflow.NodeType]bool)
	for _, node := range wf.Nodes {
		if seenTypes[node.Type] {
			continue
		}
		seenTypes[node.Type] = true
		files = append(files, g.generateModuleFile(node))
	}

	// utils.py
	files = append(files, compiler.GeneratedFile{
		Path: "src/utils.py",
		Content: `"""Utility functions for the AIStudio generated project."""

import os
import yaml
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def load_config(path: str = None) -> dict:
    """Load configuration from YAML file."""
    if path is None:
        path = Path(__file__).parent.parent / "config" / "config.yaml"
    if os.path.exists(path):
        with open(path, "r") as f:
            return yaml.safe_load(f)
    return {}


def ensure_dir(path: str) -> str:
    """Ensure a directory exists, creating it if necessary."""
    os.makedirs(path, exist_ok=True)
    return path
`,
		Mode: 0644,
	})

	return files
}

func (g *Generator) generateModuleFile(node workflow.Node) compiler.GeneratedFile {
	moduleName := sanitizeName(node.Name)
	content := fmt.Sprintf(`"""%s module - generated from workflow node %s."""

import logging
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class %s:
    """%s workflow node implementation."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        logger.info("Initialized %%s with config: %%s", self.__class__.__name__, self.config)

    def execute(self, **inputs) -> Dict[str, Any]:
        """
        Execute the %s node.
        
        Args:
            **inputs: Input data from upstream nodes.
            
        Returns:
            Output data for downstream nodes.
        """
        logger.info("Executing %%s", self.__class__.__name__)
        return self._process(inputs)

    def _process(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        """Process inputs and produce outputs."""
        # TODO: Implement node logic
        return {"output": inputs}
`, moduleName, node.ID, strings.Title(moduleName), node.Name, node.Name)

	return compiler.GeneratedFile{
		Path: fmt.Sprintf("src/%s.py", moduleName),
		Content: content,
		Mode: 0644,
	}
}

func (g *Generator) generateTestFiles() []compiler.GeneratedFile {
	return []compiler.GeneratedFile{
		{
			Path: "tests/__init__.py",
			Content: `"""Test package for AIStudio generated project."""`,
			Mode: 0644,
		},
		{
			Path: "tests/test_main.py",
			Content: `"""Tests for main entry point."""

import unittest
from pathlib import Path


class TestMain(unittest.TestCase):
    """Test the main module."""

    def test_project_structure(self):
        """Verify project structure exists."""
        self.assertTrue(Path("src").exists())
        self.assertTrue(Path("config").exists())
        self.assertTrue(Path("main.py").exists())


if __name__ == "__main__":
    unittest.main()
`,
			Mode: 0644,
		},
	}
}

func (g *Generator) generateWorkflowCopy(wf *workflow.Workflow) []compiler.GeneratedFile {
	data, err := workflow.ToJSON(wf)
	if err != nil {
		return nil
	}
	return []compiler.GeneratedFile{
		{Path: ".aistudio/workflow.json", Content: string(data), Mode: 0644},
	}
}

// ============================================================================
// Helper Functions
// ============================================================================

func (g *Generator) collectPackages(wf *workflow.Workflow) []string {
	// Collect Python packages based on node types
	pkgs := []string{
		"pyyaml>=6.0",
	}

	for _, node := range wf.Nodes {
		switch node.Type {
		case workflow.NodeTypeModelTrainer:
			pkgs = append(pkgs, "torch>=2.0.0")
			pkgs = append(pkgs, "torchvision>=0.15.0")
		case workflow.NodeTypeModelInference:
			pkgs = append(pkgs, "torch>=2.0.0")
		case workflow.NodeTypeDataLoader:
			pkgs = append(pkgs, "numpy>=1.24.0")
		case workflow.NodeTypeDataPreprocess:
			pkgs = append(pkgs, "numpy>=1.24.0")
			pkgs = append(pkgs, "scikit-learn>=1.3.0")
		case workflow.NodeTypeVisualization:
			pkgs = append(pkgs, "matplotlib>=3.7.0")
		case workflow.NodeTypeHyperparamTune:
			pkgs = append(pkgs, "optuna>=3.0.0")
		}
	}

	return uniqueStrings(pkgs)
}

func (g *Generator) requiresGPU(wf *workflow.Workflow) bool {
	for _, node := range wf.Nodes {
		if node.Type == workflow.NodeTypeModelTrainer {
			if device, ok := node.Config["device"]; ok {
				if deviceStr, ok := device.(string); ok && deviceStr == "cuda" {
					return true
				}
			}
		}
	}
	return false
}

func sanitizeName(name string) string {
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, " ", "_")
	name = strings.ReplaceAll(name, "-", "_")
	// Remove non-alphanumeric characters
	var result []rune
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			result = append(result, r)
		}
	}
	return string(result)
}

func sanitizeFuncName(name string) string {
	name = strings.Title(sanitizeName(name))
	return name
}

func uniqueStrings(s []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, v := range s {
		if !seen[v] {
			seen[v] = true
			result = append(result, v)
		}
	}
	return result
}

// Template functions
var templateFuncs = template.FuncMap{
	"title": strings.Title,
	"lower": strings.ToLower,
	"upper": strings.ToUpper,
}