import type {
  Plugin,
  PluginCategoryGroup,
  InstallStep,
  AgentInvocation,
} from './types'

export const mockCategoryGroups: PluginCategoryGroup[] = [
  { category: 'vision', label: 'AI Vision', icon: 'M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z M11 12a2 2 0 1 0 4 0 2 2 0 0 0-4 0z', color: 'var(--vision)' },
  { category: 'nlp', label: 'NLP', icon: 'M4 7V4h16v3M9 20h6M12 4v16', color: 'var(--nlp)' },
  { category: 'timeseries', label: 'Time Series', icon: 'M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z M12 6v6l4 2', color: 'var(--timeseries)' },
  { category: 'speech', label: 'Speech', icon: 'M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z M19 10v2a7 7 0 0 1-14 0v-2 M12 19v4M8 23h8', color: 'var(--nlp)' },
  { category: 'simulation', label: 'Simulation', icon: 'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z', color: 'var(--simulation)' },
  { category: 'system', label: 'System', icon: 'M4 17l6-6-6-6M12 19h8', color: 'var(--system)' },
  { category: 'mcp', label: 'MCP', icon: 'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71 M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71', color: 'var(--mcp)' },
]

export const mockPlugins: Plugin[] = [
  {
    id: 'yolov8',
    name: 'YOLOv8',
    version: '8.2.0',
    author: 'ultralytics',
    source: 'github',
    sourceUrl: 'https://github.com/ultralytics/ultralytics',
    description: 'YOLOv8 object detection model. State-of-the-art real-time object detection and image segmentation model for computer vision tasks.',
    category: 'vision',
    icon: 'M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z M11 12a2 2 0 1 0 4 0 2 2 0 0 0-4 0z',
    status: 'installed',
    capabilities: ['Image Detection', 'Training', 'Export', 'Inference'],
    workflowNodes: [
      { name: 'YOLO Train', type: 'train', category: 'vision' },
      { name: 'YOLO Detect', type: 'detect', category: 'vision' },
      { name: 'YOLO Export', type: 'export', category: 'vision' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'PyTorch', versionRequired: '≥2.0', versionInstalled: '2.1.0', status: 'satisfied' },
      { name: 'CUDA', versionRequired: '≥11.8', versionInstalled: '12.1', status: 'satisfied' },
      { name: 'OpenCV', versionRequired: '≥4.8', status: 'not-installed' },
    ],
    agentTools: [
      { name: 'YOLO Detection', description: 'Detect objects in images', parameters: [{ name: 'image', type: 'image', required: true, description: 'Input image' }, { name: 'confidence', type: 'number', required: false, description: 'Confidence threshold' }], returns: 'json' },
      { name: 'YOLO Training', description: 'Train custom YOLO models', parameters: [{ name: 'dataset', type: 'string', required: true, description: 'Dataset path' }, { name: 'epochs', type: 'number', required: false, description: 'Number of epochs' }], returns: 'model' },
      { name: 'Model Export', description: 'Export model to various formats', parameters: [{ name: 'format', type: 'string', required: true, description: 'Export format' }], returns: 'file' },
    ],
    tags: ['Vision', 'Detection', 'CUDA'],
    installedAt: '2025-06-15T10:30:00Z',
    updatedAt: '2025-07-01T08:00:00Z',
  },
  {
    id: 'sam',
    name: 'SAM',
    version: '1.2.0',
    author: 'Meta AI',
    source: 'github',
    sourceUrl: 'https://github.com/facebookresearch/segment-anything',
    description: 'Segment Anything Model. Universal image segmentation model that can segment any object in any image with zero-shot capabilities.',
    category: 'vision',
    icon: 'M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z M11 12a2 2 0 1 0 4 0 2 2 0 0 0-4 0z',
    status: 'installed',
    capabilities: ['Image Segmentation', 'Point Prompt', 'Box Prompt', 'Automatic Mask'],
    workflowNodes: [
      { name: 'SAM Segment', type: 'segment', category: 'vision' },
      { name: 'SAM Prompt', type: 'prompt', category: 'vision' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'PyTorch', versionRequired: '≥2.0', versionInstalled: '2.1.0', status: 'satisfied' },
      { name: 'CUDA', versionRequired: '≥11.8', versionInstalled: '12.1', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'SAM Segmentation', description: 'Segment objects in images', parameters: [{ name: 'image', type: 'image', required: true }, { name: 'points', type: 'json', required: false }], returns: 'json' },
    ],
    tags: ['Vision', 'Segmentation'],
    installedAt: '2025-06-20T14:00:00Z',
  },
  {
    id: 'rt-detr',
    name: 'RT-DETR',
    version: '2.0.0',
    author: 'Baidu',
    source: 'github',
    sourceUrl: 'https://github.com/lyuwenyu/RT-DETR',
    description: 'Real-Time DEtection TRansformer. Real-time end-to-end object detection model based on DETR architecture.',
    category: 'vision',
    icon: 'M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z M11 12a2 2 0 1 0 4 0 2 2 0 0 0-4 0z',
    status: 'not-installed',
    capabilities: ['Real-time Detection', 'End-to-End', 'Transformer'],
    workflowNodes: [
      { name: 'RT-DETR Detect', type: 'detect', category: 'vision' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'PyTorch', versionRequired: '≥2.0', versionInstalled: '2.1.0', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'RT-DETR Detection', description: 'Real-time object detection', parameters: [{ name: 'image', type: 'image', required: true }], returns: 'json' },
    ],
    tags: ['Vision', 'DETR'],
  },
  {
    id: 'transformer',
    name: 'Transformer',
    version: '4.36.0',
    author: 'Hugging Face',
    source: 'github',
    sourceUrl: 'https://github.com/huggingface/transformers',
    description: 'Hugging Face Transformers library. State-of-the-art NLP models for text classification, NER, summarization, translation, and more.',
    category: 'nlp',
    icon: 'M4 7V4h16v3M9 20h6M12 4v16',
    status: 'installed',
    capabilities: ['Text Classification', 'NER', 'Summarization', 'Translation', 'Q&A'],
    workflowNodes: [
      { name: 'Text Classify', type: 'classify', category: 'nlp' },
      { name: 'NER Extract', type: 'ner', category: 'nlp' },
      { name: 'Summarize', type: 'summarize', category: 'nlp' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'PyTorch', versionRequired: '≥2.0', versionInstalled: '2.1.0', status: 'satisfied' },
      { name: 'Tokenizers', versionRequired: '≥0.15', status: 'not-installed' },
    ],
    agentTools: [
      { name: 'Text Classification', description: 'Classify text into categories', parameters: [{ name: 'text', type: 'text', required: true }, { name: 'model', type: 'string', required: false }], returns: 'json' },
      { name: 'NER Extraction', description: 'Extract named entities', parameters: [{ name: 'text', type: 'text', required: true }], returns: 'json' },
    ],
    tags: ['NLP', 'Transformer', 'HuggingFace'],
    installedAt: '2025-05-10T09:00:00Z',
  },
  {
    id: 'llm',
    name: 'LLM Runtime',
    version: '0.5.0',
    author: 'AIStudio',
    source: 'local',
    sourceUrl: '',
    description: 'Large Language Model runtime. Support for running local LLMs with quantization, LoRA adapters, and inference optimization.',
    category: 'nlp',
    icon: 'M4 7V4h16v3M9 20h6M12 4v16',
    status: 'not-installed',
    capabilities: ['Text Generation', 'Chat Completion', 'LoRA', 'Quantization'],
    workflowNodes: [
      { name: 'LLM Generate', type: 'generate', category: 'nlp' },
      { name: 'LLM Chat', type: 'chat', category: 'nlp' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.10', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'CUDA', versionRequired: '≥12.0', versionInstalled: '12.1', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'LLM Generation', description: 'Generate text with LLM', parameters: [{ name: 'prompt', type: 'text', required: true }], returns: 'text' },
    ],
    tags: ['NLP', 'LLM', 'Local'],
  },
  {
    id: 'lstm',
    name: 'LSTM',
    version: '2.1.0',
    author: 'AIStudio',
    source: 'local',
    sourceUrl: '',
    description: 'Long Short-Term Memory network for time series forecasting. Supports multivariate prediction, sequence classification, and anomaly detection.',
    category: 'timeseries',
    icon: 'M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z M12 6v6l4 2',
    status: 'installed',
    capabilities: ['Time Series Forecasting', 'Sequence Classification', 'Anomaly Detection'],
    workflowNodes: [
      { name: 'LSTM Forecast', type: 'forecast', category: 'timeseries' },
      { name: 'LSTM Classify', type: 'classify', category: 'timeseries' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'PyTorch', versionRequired: '≥2.0', versionInstalled: '2.1.0', status: 'satisfied' },
      { name: 'numpy', versionRequired: '≥1.24', versionInstalled: '1.23.0', status: 'version-mismatch' },
    ],
    agentTools: [
      { name: 'LSTM Forecast', description: 'Forecast time series data', parameters: [{ name: 'data', type: 'json', required: true }, { name: 'horizon', type: 'number', required: false }], returns: 'json' },
    ],
    tags: ['TimeSeries', 'Forecasting'],
    installedAt: '2025-06-01T11:00:00Z',
  },
  {
    id: 'whisper',
    name: 'Whisper',
    version: '3.0.0',
    author: 'OpenAI',
    source: 'github',
    sourceUrl: 'https://github.com/openai/whisper',
    description: 'Whisper speech recognition model. Robust speech recognition via large-scale weak supervision with multilingual support.',
    category: 'speech',
    icon: 'M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z M19 10v2a7 7 0 0 1-14 0v-2 M12 19v4M8 23h8',
    status: 'not-installed',
    capabilities: ['Speech to Text', 'Translation', 'Language Detection'],
    workflowNodes: [
      { name: 'Whisper Transcribe', type: 'transcribe', category: 'speech' },
      { name: 'Whisper Translate', type: 'translate', category: 'speech' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'PyTorch', versionRequired: '≥2.0', versionInstalled: '2.1.0', status: 'satisfied' },
      { name: 'FFmpeg', versionRequired: '≥4.0', status: 'not-installed' },
    ],
    agentTools: [
      { name: 'Speech to Text', description: 'Transcribe audio to text', parameters: [{ name: 'audio', type: 'file', required: true }, { name: 'language', type: 'string', required: false }], returns: 'text' },
    ],
    tags: ['Speech', 'ASR', 'Multilingual'],
  },
  {
    id: 'sumo',
    name: 'SUMO',
    version: '1.19.0',
    author: 'DLR',
    source: 'github',
    sourceUrl: 'https://github.com/eclipse/sumo',
    description: 'Simulation of Urban MObility. Microscopic traffic simulation package for large networks with multimodal transport.',
    category: 'simulation',
    icon: 'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z',
    status: 'installed',
    capabilities: ['Traffic Simulation', 'Route Planning', 'Emission Modeling', 'GUI'],
    workflowNodes: [
      { name: 'SUMO Simulate', type: 'simulate', category: 'simulation' },
      { name: 'SUMO Analyze', type: 'analyze', category: 'simulation' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
      { name: 'SUMO Binary', versionRequired: '≥1.18', versionInstalled: '1.19', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'Traffic Simulation', description: 'Run traffic simulation', parameters: [{ name: 'network', type: 'file', required: true }, { name: 'duration', type: 'number', required: false }], returns: 'json' },
    ],
    tags: ['Simulation', 'Traffic'],
    installedAt: '2025-05-20T16:00:00Z',
  },
  {
    id: 'vissim',
    name: 'VISSIM',
    version: '1.0.0',
    author: 'PTV',
    source: 'local',
    sourceUrl: '',
    description: 'PTV VISSIM connector. Microscopic traffic simulation with multimodal traffic flow modeling and visualization.',
    category: 'simulation',
    icon: 'M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z',
    status: 'not-installed',
    capabilities: ['Micro Simulation', 'Traffic Flow', 'Visualization'],
    workflowNodes: [
      { name: 'VISSIM Simulate', type: 'simulate', category: 'simulation' },
    ],
    dependencies: [
      { name: 'VISSIM', versionRequired: '≥2023', status: 'not-installed' },
      { name: 'Python', versionRequired: '≥3.8', versionInstalled: '3.11.2', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'VISSIM Simulation', description: 'Run VISSIM traffic simulation', parameters: [{ name: 'project', type: 'file', required: true }], returns: 'json' },
    ],
    tags: ['Simulation', 'VISSIM'],
  },
  {
    id: 'cuda',
    name: 'CUDA Toolkit',
    version: '12.1.0',
    author: 'NVIDIA',
    source: 'local',
    sourceUrl: '',
    description: 'CUDA parallel computing platform. GPU-accelerated computing for AI/ML workloads with cuDNN and TensorRT support.',
    category: 'system',
    icon: 'M4 17l6-6-6-6M12 19h8',
    status: 'installed',
    capabilities: ['GPU Computing', 'cuDNN', 'TensorRT', 'NVCC'],
    workflowNodes: [],
    dependencies: [
      { name: 'NVIDIA Driver', versionRequired: '≥525', versionInstalled: '535', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'GPU Status', description: 'Check GPU status', parameters: [], returns: 'json' },
    ],
    tags: ['System', 'GPU', 'CUDA'],
    installedAt: '2025-04-01T08:00:00Z',
  },
  {
    id: 'docker',
    name: 'Docker',
    version: '24.0.0',
    author: 'Docker Inc.',
    source: 'local',
    sourceUrl: '',
    description: 'Docker container runtime. Containerized environment management for isolated plugin execution and reproducible builds.',
    category: 'system',
    icon: 'M4 17l6-6-6-6M12 19h8',
    status: 'not-installed',
    capabilities: ['Container Runtime', 'Image Management', 'Network', 'Volume'],
    workflowNodes: [],
    dependencies: [
      { name: 'Docker Engine', versionRequired: '≥24.0', status: 'not-installed' },
    ],
    agentTools: [
      { name: 'Container Management', description: 'Manage Docker containers', parameters: [{ name: 'action', type: 'string', required: true }], returns: 'json' },
    ],
    tags: ['System', 'Docker', 'Container'],
  },
  {
    id: 'mcp-tools',
    name: 'MCP Tools',
    version: '1.0.0',
    author: 'AIStudio',
    source: 'local',
    sourceUrl: '',
    description: 'Model Context Protocol tools. Standardized tool interface for AI agents with server management and tool discovery.',
    category: 'mcp',
    icon: 'M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71 M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71',
    status: 'installed',
    capabilities: ['Tool Discovery', 'Server Management', 'Protocol Bridge'],
    workflowNodes: [
      { name: 'MCP Call', type: 'call', category: 'mcp' },
    ],
    dependencies: [
      { name: 'Python', versionRequired: '≥3.10', versionInstalled: '3.11.2', status: 'satisfied' },
    ],
    agentTools: [
      { name: 'MCP Tool Call', description: 'Call MCP server tools', parameters: [{ name: 'server', type: 'string', required: true }, { name: 'tool', type: 'string', required: true }], returns: 'json' },
    ],
    tags: ['MCP', 'Protocol', 'Agent'],
    installedAt: '2025-06-25T12:00:00Z',
  },
]

export function createMockInstallSteps(pluginName: string): InstallStep[] {
  return [
    { id: 's1', name: `Checking Dependencies`, status: 'pending', logs: [] },
    { id: 's2', name: `Checking Environment`, status: 'pending', logs: [] },
    { id: 's3', name: `Creating Environment`, status: 'pending', logs: [] },
    { id: 's4', name: `Installing Dependencies`, status: 'pending', logs: [] },
    { id: 's5', name: `Downloading Source`, status: 'pending', logs: [] },
    { id: 's6', name: `Downloading Model`, status: 'pending', logs: [] },
    { id: 's7', name: `Configuring Plugin`, status: 'pending', logs: [] },
    { id: 's8', name: `Registering Workflow Nodes`, status: 'pending', logs: [] },
    { id: 's9', name: `Registering Agent Tools`, status: 'pending', logs: [] },
    { id: 's10', name: `Verifying Installation`, status: 'pending', logs: [] },
  ]
}

export const mockInvocations: AgentInvocation[] = [
  {
    id: 'inv-1',
    pluginId: 'yolov8',
    userMessage: '训练车辆检测模型',
    agentResponse: 'Selected: YOLOv8 Plugin',
    workflowGenerated: ['Dataset', 'YOLOv8 Train', 'Export'],
    timestamp: '2025-07-05T14:30:00Z',
  },
  {
    id: 'inv-2',
    pluginId: 'yolov8',
    userMessage: '检测图片中的车辆',
    agentResponse: 'Using tool: YOLO Detection',
    toolUsed: 'YOLO Detection',
    result: '12 objects detected',
    timestamp: '2025-07-05T15:00:00Z',
  },
]