# -*- coding: utf-8 -*-
# Generated by the gRPC protocol buffer compiler.  DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import aiengine_pb2 as aiengine__pb2


class AIEngineStub(object):
    """AIEngine service definition."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
            '/aiengine.AIEngine/ExecuteTask',
            request_serializer=aiengine__pb2.TaskRequest.SerializeToString,
            response_deserializer=aiengine__pb2.TaskResponse.FromString,
        )
        self.GetModelStatus = channel.unary_unary(
            '/aiengine.AIEngine/GetModelStatus',
            request_serializer=aiengine__pb2.ModelStatusRequest.SerializeToString,
            response_deserializer=aiengine__pb2.ModelStatusResponse.FromString,
        )
        self.LoadModel = channel.unary_unary(
            '/aiengine.AIEngine/LoadModel',
            request_serializer=aiengine__pb2.LoadModelRequest.SerializeToString,
            response_deserializer=aiengine__pb2.LoadModelResponse.FromString,
        )
        self.UnloadModel = channel.unary_unary(
            '/aiengine.AIEngine/UnloadModel',
            request_serializer=aiengine__pb2.UnloadModelRequest.SerializeToString,
            response_deserializer=aiengine__pb2.UnloadModelResponse.FromString,
        )
        self.HealthCheck = channel.unary_unary(
            '/aiengine.AIEngine/HealthCheck',
            request_serializer=aiengine__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=aiengine__pb2.HealthCheckResponse.FromString,
        )


class AIEngineServicer(object):
    """AIEngine service definition."""

    def ExecuteTask(self, request, context):
        """Execute an AI task."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Get model status."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Load a model."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Unload a model."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


class AIEngineServicerToServer(object):
    """gRPC server helper: adds AIEngineServicer to a grpc.Server."""

    @staticmethod
    def add_to_server(servicer, server):
        from grpc import unary_unary_rpc_method_handler
        rpc_method_handlers = {
            'ExecuteTask': unary_unary_rpc_method_handler(
                servicer.ExecuteTask,
                request_deserializer=aiengine__pb2.TaskRequest.FromString,
                response_serializer=aiengine__pb2.TaskResponse.SerializeToString,
            ),
            'GetModelStatus': unary_unary_rpc_method_handler(
                servicer.GetModelStatus,
                request_deserializer=aiengine__pb2.ModelStatusRequest.FromString,
                response_serializer=aiengine__pb2.ModelStatusResponse.SerializeToString,
            ),
            'LoadModel': unary_unary_rpc_method_handler(
                servicer.LoadModel,
                request_deserializer=aiengine__pb2.LoadModelRequest.FromString,
                response_serializer=aiengine__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': unary_unary_rpc_method_handler(
                servicer.UnloadModel,
                request_deserializer=aiengine__pb2.UnloadModelRequest.FromString,
                response_serializer=aiengine__pb2.UnloadModelResponse.SerializeToString,
            ),
            'HealthCheck': unary_unary_rpc_method_handler(
                servicer.HealthCheck,
                request_deserializer=aiengine__pb2.HealthCheckRequest.FromString,
                response_serializer=aiengine__pb2.HealthCheckResponse.SerializeToString,
            ),
        }
        generic_handler = grpc.method_service_handler('aiengine.AIEngine', rpc_method_handlers)
        server.add_generic_rpc_handlers((generic_handler,))
