// Package compiler transforms Workflow DSL into real engineering projects.
//
// The Compiler is the heart of AIStudio V2. It reads a declarative Workflow,
// selects the appropriate Generator, and produces a complete, runnable project
// on the filesystem that can be executed independently of AIStudio.
//
// Architecture:
//   Workflow → Compiler → Generator Registry → Generator → Project
//
// The Compiler does NOT:
//   - Execute projects (that's Runtime's job)
//   - Modify projects (that's the user's job)
//   - Install dependencies (that's Environment's job)
//   - Generate code from AI (that's Agent's job, and it only generates workflow.json)
package compiler

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/aistudio/backend/internal/eventbus"
	"github.com/aistudio/backend/internal/workflow"
)

// ============================================================================
// Compiler Interface
// ============================================================================

// Compiler compiles a Workflow into a project.
// It is the single entry point for all project generation.
type Compiler interface {
	// Compile compiles a workflow into a project directory.
	Compile(ctx context.Context, wf *workflow.Workflow, opts CompileOptions) (*CompileResult, error)

	// Plan returns a compilation plan without writing any files.
	// This is useful for dry-run mode and previewing what will be generated.
	Plan(ctx context.Context, wf *workflow.Workflow, opts CompileOptions) (*CompilePlan, error)

	// ListTargets returns all available compilation targets.
	ListTargets() []TargetInfo

	// ListAllTargets returns all available compilation targets (alias).
	ListAllTargets() []TargetInfo

	// GetGenerator returns the generator for a given target.
	GetGenerator(target workflow.Target) (Generator, bool)

	// RegisterGenerator registers a new generator.
	RegisterGenerator(g Generator) error
}

// ============================================================================
// Types
// ============================================================================

// CompileOptions controls the compilation behavior.
type CompileOptions struct {
	OutputDir   string            // Output directory for generated project
	Target      workflow.Target   // Target platform (overrides workflow target)
	Variables   map[string]string // Template variable overrides
	Force       bool              // Overwrite existing output
	DryRun      bool              // Validate without writing files
	ProjectName string            // Override project name
}

// CompileResult contains the compilation output.
type CompileResult struct {
	Target      workflow.Target       `json:"target"`
	ProjectRoot string                `json:"projectRoot"`
	EntryPoints []string              `json:"entryPoints"`
	Files       []GeneratedFile       `json:"files,omitempty"`
	RuntimeReq  *RuntimeRequirement   `json:"runtimeRequirement,omitempty"`
	Duration    time.Duration         `json:"duration"`
	WorkflowID  string                `json:"workflowId"`
	GeneratorID string                `json:"generatorId"`
	Warnings    []string              `json:"warnings,omitempty"`
}

// GeneratedFile represents a single file generated by the compiler.
type GeneratedFile struct {
	Path    string `json:"path"`    // Relative path within project
	Content string `json:"content"` // File content
	Mode    uint32 `json:"mode"`    // File permissions
}

// TargetInfo describes a compilation target.
type TargetInfo struct {
	Target      workflow.Target `json:"target"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Version     string          `json:"version"`
}

// RuntimeRequirement declares what runtime environment is needed.
type RuntimeRequirement struct {
	Name        string   `json:"name"`        // Bundle name
	Version     string   `json:"version"`     // Bundle version
	Python      string   `json:"python"`      // Python version
	Packages    []string `json:"packages"`    // Required pip packages
	Commands    []string `json:"commands"`    // Required system commands
	GPU         bool     `json:"gpu"`         // GPU required
	MinMemoryMB int      `json:"minMemoryMb"` // Minimum memory
	MinDiskMB   int      `json:"minDiskMb"`   // Minimum disk space
}

// ============================================================================
// CompilePlan — Preview of what will be generated
// ============================================================================

// CompilePlan describes what the compiler will generate before doing it.
type CompilePlan struct {
	GeneratorID    workflow.Target     `json:"generatorId"`
	GeneratorName  string              `json:"generatorName"`
	ProjectName    string              `json:"projectName"`
	OutputDir      string              `json:"outputDir"`
	EstimatedFiles int                 `json:"estimatedFiles"`
	EstimatedSizeKB int                `json:"estimatedSizeKB"`
	Validated      bool                `json:"validated"`
	Warnings       []string            `json:"warnings,omitempty"`
	RuntimeReq     *RuntimeRequirement `json:"runtimeRequirement,omitempty"`
}

// ============================================================================
// ResourceEstimate — Resource estimation
// ============================================================================

// ResourceEstimate describes estimated resources for generation.
type ResourceEstimate struct {
	EstimatedFiles  int   `json:"estimatedFiles"`
	EstimatedSizeKB int   `json:"estimatedSizeKB"`
	RequiresGPU     bool  `json:"requiresGpu"`
	MinMemoryMB     int   `json:"minMemoryMb"`
	MinDiskMB       int   `json:"minDiskMb"`
}

// ============================================================================
// Compiler Implementation
// ============================================================================

// NewCompiler creates a new Compiler with the given event bus.
func NewCompiler(bus *eventbus.EventBus) Compiler {
	return &compilerImpl{
		registry: NewRegistry(),
		bus:      bus,
	}
}

type compilerImpl struct {
	registry *GeneratorRegistry
	bus      *eventbus.EventBus
}

func (c *compilerImpl) Plan(ctx context.Context, wf *workflow.Workflow, opts CompileOptions) (*CompilePlan, error) {
	start := time.Now()

	target := wf.Target
	if opts.Target != "" {
		target = opts.Target
	}

	generator, ok := c.registry.Get(target)
	if !ok {
		return nil, fmt.Errorf("no generator registered for target %q (available: %s)", target, c.availableTargets())
	}

	warnings := []string{}
	if err := generator.Validate(wf); err != nil {
		warnings = append(warnings, err.Error())
	}

	rr, err := generator.RuntimeRequirement(wf)
	if err != nil {
		rr = nil
	}

	est, err := generator.EstimateResources(wf)
	estFiles := 0
	estSizeKB := 0
	if err == nil && est != nil {
		estFiles = est.EstimatedFiles
		estSizeKB = est.EstimatedSizeKB
	}

	projectName := opts.ProjectName
	if projectName == "" {
		projectName = sanitizeName(wf.Name)
	}

	log.Printf("[compiler] plan: %s → %s (estimated %d files, %d KB, duration=%v)",
		wf.Name, target, estFiles, estSizeKB, time.Since(start))

	return &CompilePlan{
		GeneratorID:     target,
		GeneratorName:   generator.Name(),
		ProjectName:     projectName,
		OutputDir:       opts.OutputDir,
		EstimatedFiles:  estFiles,
		EstimatedSizeKB: estSizeKB,
		Validated:       len(warnings) == 0,
		Warnings:        warnings,
		RuntimeReq:      rr,
	}, nil
}

func (c *compilerImpl) Compile(ctx context.Context, wf *workflow.Workflow, opts CompileOptions) (*CompileResult, error) {
	start := time.Now()

	target := wf.Target
	if opts.Target != "" {
		target = opts.Target
	}

	// Stage 1: Publish started event
	c.publishProgress(eventbus.TopicCompileStarted, wf.ID, target, "", 0.0, "")

	// Find generator
	generator, ok := c.registry.Get(target)
	if !ok {
		err := fmt.Errorf("no generator registered for target %q (available: %s)", target, c.availableTargets())
		c.publishProgress(eventbus.TopicCompileFailed, wf.ID, target, "", 0.0, err.Error())
		return nil, err
	}

	// Stage 2: Plan
	c.publishProgress(eventbus.TopicCompileProgress, wf.ID, target, "", 0.1, "planning")

	plan, planErr := c.Plan(ctx, wf, opts)
	if planErr != nil {
		c.publishProgress(eventbus.TopicCompileFailed, wf.ID, target, "", 0.0, planErr.Error())
		return nil, fmt.Errorf("compilation planning failed: %w", planErr)
	}

	if len(plan.Warnings) > 0 {
		for _, w := range plan.Warnings {
			log.Printf("[compiler] warning: %s", w)
		}
	}

	// Stage 3: Compile-time validation
	c.publishProgress(eventbus.TopicCompileProgress, wf.ID, target, "", 0.2, "validating host environment")

	if err := generator.CompileTimeValidate(ctx); err != nil {
		c.publishProgress(eventbus.TopicCompileFailed, wf.ID, target, "", 0.0, err.Error())
		return nil, fmt.Errorf("host validation failed: %w", err)
	}

	// Stage 4: Validate workflow
	c.publishProgress(eventbus.TopicCompileProgress, wf.ID, target, "", 0.3, "validating workflow")

	if err := generator.Validate(wf); err != nil {
		c.publishProgress(eventbus.TopicCompileFailed, wf.ID, target, "", 0.0, err.Error())
		return nil, fmt.Errorf("workflow validation failed for target %s: %w", target, err)
	}

	// Stage 5: Generate
	c.publishProgress(eventbus.TopicCompileProgress, wf.ID, target, "", 0.5, "generating project")

	genResult, err := generator.Generate(ctx, wf, opts)
	if err != nil {
		c.publishProgress(eventbus.TopicCompileFailed, wf.ID, target, "", 0.0, err.Error())
		return nil, fmt.Errorf("generation failed: %w", err)
	}

	// Stage 6: Verify
	c.publishProgress(eventbus.TopicCompileProgress, wf.ID, target, "", 0.9, "verifying output")

	var runtimeReq *RuntimeRequirement
	if rr, err := generator.RuntimeRequirement(wf); err == nil {
		runtimeReq = rr
	}

	result := &CompileResult{
		Target:      target,
		ProjectRoot: genResult.ProjectRoot,
		EntryPoints: genResult.EntryPoints,
		Files:       genResult.Files,
		RuntimeReq:  runtimeReq,
		Duration:    time.Since(start),
		WorkflowID:  wf.ID,
		GeneratorID: string(generator.ID()),
	}

	// Stage 7: Complete
	c.publishProgress(eventbus.TopicCompileCompleted, wf.ID, target, result.ProjectRoot, 1.0, result.Duration.String())

	log.Printf("[compiler] compiled workflow %s → %s project (duration=%s, files=%d)",
		wf.Name, target, result.Duration, len(result.Files))

	return result, nil
}

func (c *compilerImpl) publishProgress(topic eventbus.Topic, workflowID string, target workflow.Target, outputDir string, progress float64, message string) {
	if c.bus == nil {
		return
	}
	data := eventbus.CompileEventData{
		WorkflowID: workflowID,
		Target:     string(target),
		OutputDir:  outputDir,
		Progress:   progress,
	}
	if topic == eventbus.TopicCompileFailed {
		data.Error = message
	} else if topic == eventbus.TopicCompileCompleted {
		data.Duration = message
	}
	c.bus.Publish(topic, data)
}

func (c *compilerImpl) ListAllTargets() []TargetInfo {
	return c.ListTargets()
}

func (c *compilerImpl) availableTargets() string {
	infos := c.ListTargets()
	names := make([]string, len(infos))
	for i, info := range infos {
		names[i] = string(info.Target)
	}
	if len(names) == 0 {
		return "none"
	}
	return strings.Join(names, ", ")
}

func (c *compilerImpl) ListTargets() []TargetInfo {
	generators := c.registry.List()
	infos := make([]TargetInfo, 0, len(generators))
	for _, g := range generators {
		infos = append(infos, TargetInfo{
			Target:      g.ID(),
			Name:        g.Name(),
			Description: g.Description(),
			Version:     g.Version(),
		})
	}
	return infos
}

func (c *compilerImpl) GetGenerator(target workflow.Target) (Generator, bool) {
	return c.registry.Get(target)
}

func (c *compilerImpl) RegisterGenerator(g Generator) error {
	return c.registry.Register(g)
}

func sanitizeName(name string) string {
	result := make([]byte, 0, len(name))
	for i := 0; i < len(name); i++ {
		c := name[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-' {
			result = append(result, c)
		} else if c == ' ' {
			result = append(result, '_')
		}
	}
	if len(result) == 0 {
		return "project"
	}
	return string(result)
}
