package environment

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type ProgressFunc func(msg string, progress float64)

func InstallPython(ctx context.Context, packages []string, venvPath string, progress ProgressFunc) error {
	if progress == nil {
		progress = func(string, float64) {}
	}

	if venvPath != "" {
		progress("Creating virtual environment...", 0.0)
		if err := createVenv(ctx, venvPath); err != nil {
			return err
		}
		progress("Virtual environment created", 0.1)
	}

	total := len(packages)
	if total == 0 {
		progress("No packages to install", 1.0)
		return nil
	}

	for i, pkg := range packages {
		pct := 0.1 + (float64(i)/float64(total))*0.9
		progress(fmt.Sprintf("Installing %s...", pkg), pct)

		pipCmd := getPipCommand(venvPath)
		cmd := exec.CommandContext(ctx, pipCmd, "install", pkg)
		if output, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("pip install %s failed: %w\n%s", pkg, err, string(output))
		}
	}

	progress("All packages installed", 1.0)
	return nil
}

func InstallPip(ctx context.Context, pkg, version string, progress ProgressFunc) error {
	if progress == nil {
		progress = func(string, float64) {}
	}

	progress(fmt.Sprintf("Installing %s...", pkg), 0.0)

	spec := pkg
	if version != "" {
		spec = pkg + "==" + version
	}

	pipCmd := getPipCommand("")
	cmd := exec.CommandContext(ctx, pipCmd, "install", spec)
	output, err := cmd.CombinedOutput()
	if err != nil {
		progress(fmt.Sprintf("Failed to install %s", pkg), 0.0)
		return fmt.Errorf("pip install %s failed: %w\n%s", spec, err, string(output))
	}

	progress(fmt.Sprintf("%s installed successfully", pkg), 1.0)
	return nil
}

func GenerateInstallScript(target string) string {
	switch target {
	case "bat":
		return generateBatScript()
	case "ps1":
		return generatePs1Script()
	default:
		return generateShScript()
	}
}

func createVenv(ctx context.Context, venvPath string) error {
	pythonCmd := getPythonCommand()
	cmd := exec.CommandContext(ctx, pythonCmd, "-m", "venv", venvPath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("create venv failed: %w\n%s", err, string(output))
	}
	return nil
}

func getPythonCommand() string {
	if _, err := os.Stat(filepath.Join("Scripts", "python.exe")); err == nil {
		return filepath.Join("Scripts", "python.exe")
	}
	if _, err := os.Stat(filepath.Join("bin", "python")); err == nil {
		return filepath.Join("bin", "python")
	}
	if _, err := exec.LookPath("python3"); err == nil {
		return "python3"
	}
	return "python"
}

func getPipCommand(venvPath string) string {
	if venvPath != "" {
		if runtimeGOOS() == "windows" {
			if _, err := os.Stat(filepath.Join(venvPath, "Scripts", "pip.exe")); err == nil {
				return filepath.Join(venvPath, "Scripts", "pip.exe")
			}
		}
		if _, err := os.Stat(filepath.Join(venvPath, "bin", "pip")); err == nil {
			return filepath.Join(venvPath, "bin", "pip")
		}
	}
	if _, err := exec.LookPath("pip3"); err == nil {
		return "pip3"
	}
	return "pip"
}

func runtimeGOOS() string {
	return os.Getenv("GOOS")
}

func generateShScript() string {
	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# AIStudio Environment Setup Script\n")
	b.WriteString("# Generated by AIStudio\n\n")
	b.WriteString("set -e\n\n")
	b.WriteString("echo \"=== AIStudio Environment Setup ===\"\n\n")
	b.WriteString("# Detect Python\n")
	b.WriteString("PYTHON_CMD=\"\"\n")
	b.WriteString("if command -v python3 &> /dev/null; then\n")
	b.WriteString("  PYTHON_CMD=\"python3\"\n")
	b.WriteString("elif command -v python &> /dev/null; then\n")
	b.WriteString("  PYTHON_CMD=\"python\"\n")
	b.WriteString("else\n")
	b.WriteString("  echo \"Error: Python not found\"\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n\n")
	b.WriteString("# Check pip\n")
	b.WriteString("if ! command -v pip3 &> /dev/null && ! command -v pip &> /dev/null; then\n")
	b.WriteString("  echo \"Installing pip...\"\n")
	b.WriteString("  $PYTHON_CMD -m ensurepip --upgrade\n")
	b.WriteString("fi\n\n")
	b.WriteString("# Create virtual environment (optional)\n")
	b.WriteString("if [ ! -d \"venv\" ]; then\n")
	b.WriteString("  echo \"Creating virtual environment...\"\n")
	b.WriteString("  $PYTHON_CMD -m venv venv\n")
	b.WriteString("  source venv/bin/activate\n")
	b.WriteString("fi\n\n")
	b.WriteString("# Install requirements\n")
	b.WriteString("echo \"Installing dependencies...\"\n")
	b.WriteString("pip install -r requirements.txt 2>/dev/null || echo \"No requirements.txt found\"\n\n")
	b.WriteString("echo \"=== Setup Complete ===\"\n")
	return b.String()
}

func generateBatScript() string {
	var b strings.Builder
	b.WriteString("@echo off\n")
	b.WriteString("REM AIStudio Environment Setup Script\n")
	b.WriteString("REM Generated by AIStudio\n\n")
	b.WriteString("echo === AIStudio Environment Setup ===\n\n")
	b.WriteString("REM Check Python\n")
	b.WriteString("python --version >nul 2>&1\n")
	b.WriteString("if errorlevel 1 (\n")
	b.WriteString("  echo Error: Python not found\n")
	b.WriteString("  exit /b 1\n")
	b.WriteString(")\n\n")
	b.WriteString("REM Create virtual environment\n")
	b.WriteString("if not exist \"venv\\Scripts\\python.exe\" (\n")
	b.WriteString("  echo Creating virtual environment...\n")
	b.WriteString("  python -m venv venv\n")
	b.WriteString(")\n\n")
	b.WriteString("REM Activate virtual environment\n")
	b.WriteString("call venv\\Scripts\\activate.bat\n\n")
	b.WriteString("REM Upgrade pip\n")
	b.WriteString("python -m pip install --upgrade pip\n\n")
	b.WriteString("REM Install requirements\n")
	b.WriteString("if exist requirements.txt (\n")
	b.WriteString("  echo Installing dependencies...\n")
	b.WriteString("  pip install -r requirements.txt\n")
	b.WriteString(")\n\n")
	b.WriteString("echo === Setup Complete ===\n")
	return b.String()
}

func generatePs1Script() string {
	var b strings.Builder
	b.WriteString("# AIStudio Environment Setup Script\n")
	b.WriteString("# Generated by AIStudio\n\n")
	b.WriteString("Write-Host \"=== AIStudio Environment Setup ===\" -ForegroundColor Cyan\n\n")
	b.WriteString("# Check Python\n")
	b.WriteString("try {\n")
	b.WriteString("  $pythonVersion = python --version\n")
	b.WriteString("  Write-Host \"Python: $pythonVersion\"\n")
	b.WriteString("} catch {\n")
	b.WriteString("  Write-Host \"Error: Python not found\" -ForegroundColor Red\n")
	b.WriteString("  exit 1\n")
	b.WriteString("}\n\n")
	b.WriteString("# Create virtual environment\n")
	b.WriteString("if (-not (Test-Path \"venv\\Scripts\\python.exe\")) {\n")
	b.WriteString("  Write-Host \"Creating virtual environment...\"\n")
	b.WriteString("  python -m venv venv\n")
	b.WriteString("}\n\n")
	b.WriteString("# Activate and install\n")
	b.WriteString("& \".\\venv\\Scripts\\Activate.ps1\"\n\n")
	b.WriteString("Write-Host \"Upgrading pip...\"\n")
	b.WriteString("python -m pip install --upgrade pip\n\n")
	b.WriteString("if (Test-Path \"requirements.txt\") {\n")
	b.WriteString("  Write-Host \"Installing dependencies...\"\n")
	b.WriteString("  pip install -r requirements.txt\n")
	b.WriteString("}\n\n")
	b.WriteString("Write-Host \"=== Setup Complete ===\" -ForegroundColor Green\n")
	return b.String()
}
