package compiler

import (
	"time"

	"github.com/aistudio/packages/workflow"
)

// CompileOptions controls the compilation behavior.
type CompileOptions struct {
	OutputDir   string            // Output directory for generated project
	Target      workflow.Target   // Target platform (overrides workflow target)
	Variables   map[string]string // Template variable overrides
	Force       bool              // Overwrite existing output
	DryRun      bool              // Validate without writing files
	ProjectName string            // Override project name
}

// CompileResult contains the compilation output.
type CompileResult struct {
	Target      workflow.Target     `json:"target"`
	ProjectRoot string              `json:"projectRoot"`
	EntryPoints []string            `json:"entryPoints"`
	Files       []GeneratedFile     `json:"files,omitempty"`
	RuntimeReq  *RuntimeRequirement `json:"runtimeRequirement,omitempty"`
	Duration    time.Duration       `json:"duration"`
	WorkflowID  string              `json:"workflowId"`
	GeneratorID string              `json:"generatorId"`
	Warnings    []string            `json:"warnings,omitempty"`
}

// GeneratedFile represents a single file generated by the compiler.
type GeneratedFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
	Mode    uint32 `json:"mode"`
}

// TargetInfo describes a compilation target.
type TargetInfo struct {
	Target      workflow.Target `json:"target"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Version     string          `json:"version"`
}

// RuntimeRequirement declares what runtime environment is needed.
type RuntimeRequirement struct {
	Name        string   `json:"name"`
	Version     string   `json:"version"`
	Python      string   `json:"python"`
	Packages    []string `json:"packages"`
	Commands    []string `json:"commands"`
	GPU         bool     `json:"gpu"`
	MinMemoryMB int      `json:"minMemoryMb"`
	MinDiskMB   int      `json:"minDiskMb"`
}

// CompilePlan describes what the compiler will generate before doing it.
type CompilePlan struct {
	GeneratorID     workflow.Target     `json:"generatorId"`
	GeneratorName   string              `json:"generatorName"`
	ProjectName     string              `json:"projectName"`
	OutputDir       string              `json:"outputDir"`
	EstimatedFiles  int                 `json:"estimatedFiles"`
	EstimatedSizeKB int                 `json:"estimatedSizeKB"`
	Validated       bool                `json:"validated"`
	Warnings        []string            `json:"warnings,omitempty"`
	RuntimeReq      *RuntimeRequirement `json:"runtimeRequirement,omitempty"`
}

// ResourceEstimate describes estimated resources for generation.
type ResourceEstimate struct {
	EstimatedFiles  int  `json:"estimatedFiles"`
	EstimatedSizeKB int  `json:"estimatedSizeKB"`
	RequiresGPU     bool `json:"requiresGpu"`
	MinMemoryMB     int  `json:"minMemoryMb"`
	MinDiskMB       int  `json:"minDiskMb"`
}

// GenerateResult contains the generation output from a generator.
type GenerateResult struct {
	Target      workflow.Target `json:"target"`
	ProjectRoot string          `json:"projectRoot"`
	EntryPoints []string        `json:"entryPoints"`
	Files       []GeneratedFile `json:"files"`
	ProjectName string          `json:"projectName"`
}